
title: Cuervo · Portafolio
email: danielcuervor01@gmail.com
description: >-
  Portafolio técnico de Cuervo — integración de física, robótica, software y neurociencia. De la idea al prototipo funcional.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://corvo001.github.io" # change to your GitHub Pages URL
repository: corvo001/corvo001.github.io

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Minimal Mistakes settings
minimal_mistakes_skin: "default"
locale: "es-ES"
name: "Cuervo"
logo: "/assets/images/avatar.png"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Analytics (opcional)
analytics:
  provider: false

# Author
author:
  name: "Cuervo"
  avatar: "/assets/images/avatar.png"
  bio: "Creador tecnológico. Robótica, software, física y neurociencia. Diseño y construyo tecnología con rigor científico."
  location: "España"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/corvo001"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/danielcuervor/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:danielcuervor01@gmail.com"

# Navigation
collections:
  posts:
    output: true
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: false
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
